language: ruby
rvm:
  - 2.1.2
cache:
  bundler: true
  apt: true
  directories:
  - /usr/local
env:
  global:
    - LUAROCKS_VERSION=2.2.0
    - OPENRESTY_VERSION=1.7.2.1
    - OPENRESTY=/usr/local/openresty
    - PATH=$PATH:/opt/apitools-monitor/embedded/bin
before_install:
  - curl -q https://packagecloud.io/install/repositories/APItools/monitor/script.deb | sudo bash
  - sudo apt-get -y install make unzip apitools-monitor
install:
  - bundle install
  - make dependencies
script: make
